### ISSUE TITLE
UI: Friends List for group appointment

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#10]
Need some mock up dataset for setting up an appointment for a group of people.

**Comment by dr72** [comment]
### Task Test

1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press Appointment/Meeting to navigate to appointments.
5. View list of friends you can create appointments with.
