### ISSUE TITLE
Application Color

### ISSUE THREAD

**Issue by mzhang54** [cse442-at-ub/cse442-semester-project-368#15]
As a user, I want to have a better color used in the application, so that I become satisfied with its beautiful aesthetics and willing to use it more often.

**Comment by cjw531** [comment]
### Acceptance Test

1. Once you open the application, the color should be changed to the fashionable ones, the blue colored toolbars with yellow colored highlights, from the Android default green colored theme.
2. This color should be **consistent** in all other pages as well
3. You may even now see the floating button located in right-bottom corner became prettier than before
