### ISSUE TITLE
Navigation Bar Highlights

### ISSUE THREAD

**Issue by mzhang54** [cse442-at-ub/cse442-semester-project-368#18]
We need to highlight the current menu/page that user is in, by highlighting the name of the page on the navigation bar on the left side.

**Comment by cjw531** [comment]
### Task Test:

1. Login with any characters for email and any password > 5 characters.
2. Go to a page/menu that you would like to be in, by using the navigation bar. 
3. Try to navigate to another page, and click the navigation bar on top left corner.
4. You may see where you at by seeing the highlighted menu -the current menu that you are in will be colored into green, while other menus are remain gray color.
5. This let the user know where they are right now, avoid them to get lost.
