### ISSUE TITLE
UI: Appointment/Meeting with other friend.

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#19]
As a user, I want to see the common available time slot between me and my friends, so that I can make an appointment with them based on this data.

**Comment by cjw531** [comment]
### Acceptance Test:

1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press friends to navigate to "Appointment/"Meeting
5. Press on a friends name to see their available schedule -will not show conflicting time with you.
6. You can click the time slot to add a new schedule with them. 

*The available time that is showing right now is not an actual data. You cannot make an actually appointment too for now.
