### ISSUE TITLE
Add Mock Up Daily Schedule in My Schedule

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#20]
Add some mock up daily schedule in "My Schedule" page. It should be located under the remaining time widget, and only display the daily schedule.

**Comment by cjw531** [comment]
### Task Test:

Open the application.
Login with any characters for email and any password > 5 characters.
You should be in "My Schedule" page.
Press the sidebar located in the top left corner if you are not in "My Schedule" page. Please navigate to this page.
You may now see some daily schedule.

*For now, it is not an actual schedule that the user have.
