### ISSUE TITLE
Make Appointment/Meeting

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#21]
As a user, I want to make an appointment request with my friend or group, so that my friend or team can manage their schedule easily as well.

**Comment by cjw531** [comment]
### Acceptance Test

1. Go to Appointment/Meeting menu, then you should be seeing a list of friend.
2. Click friends that you wish to have appointment with. Once you click, they will colored as yellow, and if you unclick them, it will come back to the normal white color.
3. Once you are done with selecting friends, click the floating button located in right-bottom corner. You can choose them by browsing or searching with the search bar on top, as usual (#71).
4. You will be navigated to a create appointment page, that will give you a list of available time slots.
5. If you wish to stop choosing the available time slot, (for example if you forgot to choose people) you can click the <- (arrow) button located in left-top corner, anytime you want.
6. Once you have reached to this create appointment page, the first thing you should do is selecting a start date.
7. After you pick dates, you should input the duration of the meeting. Note that the meeting cannot go over 12 hours.
8. Once you select them, click "Show available times" button. Then you should be seeing a list of available times below.
9. You can select one of them, then this will navigate you to the appointment request page.
10. In this page, you can see participants, and you need to fill out the rest of the information as follows: title, start time (out of the available time block), and description (if needed).
11. Once you choose start time, you can see from and to field gets reset based on the start time that you choose.
12. Once you click 'save', your meeting request has been sent to your friends (#115). Now let's wait for their responses!
13. You can stop requesting the request by clicking 'cancel', located on top-left corner.
14. Once all of them accepted your request, the schedule will be automatically added to your schedule (#115).
