### ISSUE TITLE
Keep the user logged-in & Sign out feature

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#23]
Keep the user to be logged in, unless the user log out by himself.
Create sign out feature as well to determine whether to pop up the main My Schedule page or the log-in page when the user opens the application.

**Comment by cjw531** [comment]
### Task Test

- [ ] Create a sign-in page with a Google account
- [ ] Users' Google account (user list) should be manageable on Firebase

**Comment by cjw531** [comment]
### Task Test

- Keep the user logged-in unless the user clicks sign out button.
- If the user did not click sign out, then when the user opens the app in the next time, do not open the sign in page.
- If the user clicks log out, then in the next time he opens the application, guide him to the sign in page.
