### ISSUE TITLE
UI: Time Remaining Widget in "My Schedule" Page

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#24]
As a user, I might forget the time to meet my group, so I need the apps to remind me that is a meeting coming up.

**Comment by cjw531** [comment]
### Acceptance Test:

1. Open the application 
2. Login with any characters for email and any password > 5 characters.
3. The first page will be "My Schedule". 
4. On the very top side of the page, you can see the time left until the next upcoming schedule.

*It is currently showing the current time, and the feature will be implemented in Sprint 2.
