### ISSUE TITLE
Manage Friends with Friends List

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#26]
As a user, I want to add my friends on this application, so that I can see their schedule and create an appointment with them.

**Comment by cjw531** [comment]
### Acceptance Test

1. Navigate to "Friends" page.
2. See the existing friends list based on your connection and matched with the database.
3. The user should be able to deal with add and delete their friends whenever it is needed.
4. These user activity should be matched with the database.
