### ISSUE TITLE
Friends Searchbar on Friends List

### ISSUE THREAD

**Issue by dr72** [cse442-at-ub/cse442-semester-project-368#28]
Create a search bar for searching for people and displaying results in a user's friends list.

**Comment by cjw531** [comment]
### Task Test

1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press "Friends" to navigate to friends list
5. Press 'Q' looking search button top side. It is colored green, located right above the friends list.
6. Try to search friends.

*For now, the feature has not been implemented yet, so it can be type-able, but cannot actually search friends.
