### ISSUE TITLE
View friend's profile

### ISSUE THREAD

**Issue by dr72** [cse442-at-ub/cse442-semester-project-368#29]
Clicking on a friend on your friend's list should take you to view their profile and calendar, this is where you can remove friend as well.

**Comment by cjw531** [comment]
### Task Test
1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press friends to navigate to friends list.
5. Press on a friends name to view their profile.
