### ISSUE TITLE
Delete My Schedule

### ISSUE THREAD

**Issue by dr72** [cse442-at-ub/cse442-semester-project-368#3]
As a person with a changing schedule, I want to delete appointments from my calendar and schedule, so my groups know I am free to meet during the time.

**Comment by cjw531** [comment]
### Acceptance Test

- Navigate to the "My Schedule" page.
- Press the existing schedule -which you would like to remove- from your daily schedule list. *Note that you should go to "Calendar" page to remove schedules other than the daily one.
- An option window should pop up to you to select between: "Edit" and "Delete"
- Press delete here.
- A confirmation window will pop to re-ask whether you would like to remove it or not.
- If you confirm deletion, your schedule will be deleted, and your daily schedule list should be up-to-dated after this step.
