### ISSUE TITLE
Friend Searchbar on 'Add Friend' Floating Button

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#30]
We need to make a searchbar to search **_new_** friends once the user wants to add friends (after they click the add friend floating button in "Friends" page).

**Comment by cjw531** [comment]
### Task Test
1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press friends to navigate to friends list
5. Press button in bottom right corner.
6. Add friend screen starts.
7. Press magnifying glass icon to open a search.
