### ISSUE TITLE
Remove Friend Button

### ISSUE THREAD

**Issue by dr72** [cse442-at-ub/cse442-semester-project-368#31]
When you view your friends profile, there will be a button to remove the friend.

**Comment by cjw531** [comment]
### Task Test
1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press friends to navigate to friends list
5. Press on a friends name to view their profile
6. Press remove friend button and get response that friend is removed.
