### ISSUE TITLE
UI: Create Appointment with Multiple Friends

### ISSUE THREAD

**Issue by dr72** [cse442-at-ub/cse442-semester-project-368#34]
As a user, I want to select multiple people when making an appointment, so that I can have a group appointment with them.

**Comment by cjw531** [comment]
### Task Test
1. Open the application.
2. Press the sidebar located in the top left corner.
3. Press friends to navigate to friends list
4. Press on a friends name to view their profile
5. Press on an available time and receive feedback that an appointment has been created.

**Comment by cjw531** [comment]
### Acceptance Test:

1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press appointment/meeting to navigate to appointments/meeting activity.
5. Press button in bottom right to create an appointment.
6. Button should take you to create appointment screen.

*For now, selecting multiple people feature is not available for now. We are planning on making it available in next sprint in the create appointment screen.
