### ISSUE TITLE
UI Meeting: Book appointment with available schedule

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#35]
Inform user with a toast message (for now) once they click the available time slot from other user's schedule.

**Comment by cjw531** [comment]
### Task Test:

1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press friends to navigate to "Appointment/"Meeting
5. Press on a friends name to see their available schedule -will not show conflicting time with you.
6. You can click the time slot to add a new schedule with them.
7. For now, the user will see the toast message saying the meeting has been booked.

*It is still a mock up UI so it does not reflect an actual schedule nor make an appointment.
