### ISSUE TITLE
UI Meeting: Display Available Time

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#36]
List of available times between you and your friend, clicking on a time will bring you to schedule appointment with them.

**Comment by cjw531** [comment]
### Task Test:

1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press friends to navigate to "Appointment/"Meeting
5. Press on a friends name to see their available schedule -will not show conflicting time with you.
6. You can click the time slot to add a new schedule with them.
