### ISSUE TITLE
Reflect real time passed on My Schedule

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#38]
As a user, I want to see the updated current time on My Schedule page and re-calculate the remaining time, so that I don't have to re-launch or refresh the app every time, to update it.

**Comment by cjw531** [comment]
### Acceptance Test

1. Open "My Schedule" page
2. Keep the page for at least a minute, observe that the time (above date) has changed to show correct time and the remaining time has been shortened.
