### ISSUE TITLE
Time Remaining

### ISSUE THREAD

**Issue by dr72** [cse442-at-ub/cse442-semester-project-368#4]
As a person with an appointment, I want to see when my next appointment is, so I know how much time I have before it.

**Comment by cjw531** [comment]
### Acceptance Test

1. Navigate to the "My Schedule" page.
2. It should show a current time on top.
3. Below the current time, it has a horizontal line to divide up the current time and your daily schedule list.
4. Your daily schedule is listed below, and sorted based on the starting time.
5. Next to your schedule, on right side, it has a remaining time until the schedule begins.
6. Once the schedule started, it will get removed.
