### ISSUE TITLE
UI: Search Friend to Add

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#42]
As a user, I want to search friend, so I can eventually make an appointment with my friends after adding them.

**Comment by cjw531** [comment]
### Acceptance Test

1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Press the sidebar located in the top left corner.
4. Press friends to navigate to friends list.
5. Press button in bottom right corner to go to add friend screen.
6. Press magnifying glass in top right corner to open a search bar.
7. Type in to the search field and display results.
