### ISSUE TITLE
UI My Schedule: Time to next appointment 

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#44]
Make a mock-up UI with a text box which will be showing the remaining time to the next appointment.

**Comment by cjw531** [comment]
### Task Test:

1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Go to "My Schedule" page through menu in top left.
4. On the very top side of the page, you can see the remaining time until the next upcoming schedule.
5. It is divided by the horizontal line (between the remaining time and the today's schedule) to differentiate them.

*It is currently showing the current time. Features will be implemented later on.
