### ISSUE TITLE
UI: Add Schedule in "My Schedule"

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#45]
As a person, I want to add my schedule in "My Schedule" page, so I can quickly add my instantly created daily schedule.

**Comment by cjw531** [comment]
### Acceptance Test:

1. Open the application; Login with any characters for email and any password > 5 characters, you should be in "My Schedule" page -if you are in different page, use the navigation bar on top left corner to go to "My Schedule" page.
2. Once you navigate, it will show you a list of daily schedule with the "Add Daily Schedule" floating button in the bottom right corner, colored pink for now.
3. You may use this to add schedule, but it is only for adding the daily schedule!

*It shows add screen but it is not fully featured yet. Only the button exists for now.
