### ISSUE TITLE
Register Button

### ISSUE THREAD

**Issue by dr72** [cse442-at-ub/cse442-semester-project-368#66]
Need to add button that allows users to register their account.

**Comment by dr72** [comment]
Task Test:

Create Button on login screen to register email/password that is written in the email and password edittexts.

**error checks for:**
bad email address format
email already in use
invalid password length (less than 6 characters)

Button adds user to Firebase if information entered is good.

**Comment by DonBrant** [comment]
Password length check doesn't work properly. Users registering with a shorter password will be shown a message complaining about the password length but the registration can still go through. (I managed to register with the password 'short')
