### ISSUE TITLE
UI: Friend

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#8]
As a person who has friends, I would like to have a friends list, so I can view their profiles and make appointments with them.

**Comment by cjw531** [comment]
### Acceptance Test:

Open the application.
Login with any characters for email and any password > 5 characters.
Press the sidebar located in the top left corner.
Press friends to navigate to friends list -now you will be seeing a bunch of friends.
Press on a friends name to view their profile
View a list of friend's daily schedule.

*For now, the friends and their schedule you have are not the actual friend of yours.
